### ISSUE TITLE
3.5 - Sort options multiple shortcodes same page

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#1027]
2 shortcodes same page

EG current
[listing post_type=“property,land,commercial” status=current limit=12 tools_top=on instance_id=current]

sold
[listing post_type=“property,land,commercial” status=sold limit=12 tools_top=on instance_id=sold]
the sold sort options are not working. (not sure they work with instance_id)

**Comment by prince5ingh** [comment]
Fixed here :
https://github.com/easypropertylistings/Easy-Property-Listings/commit/58f6be24a912781b9b22e61c2fabc7128125bf24

**Comment by mervb** [comment]
Added in 3.5 was the $attributes fix
