### ISSUE TITLE
3.5 - Enhance tabs and accordion to be able to pass the default tab in the html

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#1041]
Currently the JS applies the class epl_ui_tab_menu_current to the first tab, However I i want to have 3 options and set the second as the curent both the firtst and second options become current

 https://github.com/easypropertylistings/Easy-Property-Listings/blob/master/lib/assets/js/epl.js

eg the html has two: epl_ui_tab_menu_current

```
<ul class="epl_ui_tab_menu_wrapper epl_ui_tab_menu_wrapper_horizontal">
	<li class="epl_ui_tab_menu epl_ui_tab_menu_current">
		<a class="epl-tab-item epl-tab-item--manage" href="#manage-tab">Manage</a>
	</li>
	<li class="epl_ui_tab_menu epl_ui_tab_menu_current"><a class=" epl-tab-item--buy" href="#buy-tab">Buy</a></li>
	<li class="epl_ui_tab_menu"><a class=" epl-tab-item--sell" href="#sell-tab">Sell</a></li>
	<li class="epl_ui_tab_menu"><a class=" epl-tab-item--rent" href="#rent-tab">Rent</a></li>
</ul>
```

![CleanShot 2023-02-28 at 18 08 17@2x](https://user-images.githubusercontent.com/4696393/221822920-f349359e-12da-432b-be1c-a6b54d883931.png)

**Comment by mervb** [comment]
Apply similar to the accordion JS

**Comment by prince5ingh** [comment]
done here :
https://github.com/easypropertylistings/Easy-Property-Listings/commit/4495083b1dad52904da4a65acf0461b1baed9943

**Comment by mervb** [comment]
Already added in [3.4.47](https://github.com/easypropertylistings/Easy-Property-Listings/releases/tag/3.4.47)
