### ISSUE TITLE
Any way to zoom the Property map?

### ISSUE THREAD

**Issue by horieva** [easypropertylistings/Easy-Property-Listings#1052]
Thank you for your plugin. 
I used  Impreza theme with WPBakery Page Builder and when I try to add the property map (I'm adding "HTML Element" with `[listing_element type="action" action_key="epl_property_map"]` shortcode I can't change the default zoom. 

Do you have any solution for the Zoom change? Thank you.

PS: Unfortunately, I can't use` [listing_map ...` shortcode for unknown reason.

**Comment by mervb** [comment]
​Our [Advanced Mapping](https://easypropertylistings.com.au/extensions/advanced-mapping/) add-on provides map options zoom type / etc
