### ISSUE TITLE
Filters for Property Features, Commercial Filters, Rural Features

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#132]
https://github.com/easypropertylistings/Easy-Property-Listings/blob/master/lib/includes/template-functions.php

Add Filters to the epl_property_tab_section() h5 titles

**Comment by mediatelecom** [comment]
https://github.com/mediatelecom/Easy-Property-Listings/commit/d6b8ae4eee6afb81774898b1499a56a865ab03da

**Comment by mervb** [comment]
complete

**Comment by mervb** [comment]
Added to changelog
