### ISSUE TITLE
Add Filters for Beds, Bath, Parking, Aircon, security labels

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#133]
https://github.com/easypropertylistings/Easy-Property-Listings/blob/master/lib/includes/class-property-meta.php

**Comment by mediatelecom** [comment]
https://github.com/mediatelecom/Easy-Property-Listings/commit/339057e3f2d2ce41a21578cc90c044e30ed543c6

**Comment by mervb** [comment]
complete

**Comment by mervb** [comment]
Additional filters required for the labels:

You have added filters for 

return apply_filters('epl_get_property_parking',$parking[$returntype]);

Add them to the string also, use the same filter for all in this example "Parking Spaces"

epl_get_property_parking_label as the filter name
