### ISSUE TITLE
Translation Issue with land sizes

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#137]
It seems that some translated terms don't apply.

If you look at http://www.immobasrhin.com/property/grand-corps-de-ferme-a-colombages-avec-dependances-et-piscine-sur-15-ares-a-lampertheim/ under the property characteristics it is written : "La surface du terrain est de 15 acre" where the translation of acre should be effective to "ares" 

I all ready looked all over the translation files, there is no way I missed it, as all entries are translated.
It seems to me, that the "acre" term as well as others in the configuration page don't get translated. perhaps there is a missing link.

**Comment by mediatelecom** [comment]
https://github.com/mediatelecom/Easy-Property-Listings/commit/5d498a458fef57af44d84d4e70d6ca378e828bec

**Comment by mervb** [comment]
complete

**Comment by mervb** [comment]
Add the same filter to the get_property_building_area_value unit function
