### ISSUE TITLE
Listing Search Widget duplicate ID's and stray end ul

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#138]
https://wordpress.org/support/topic/validation-errors-35

This plugin has so much potential, I hope the issues with the Listing Search Widget (awaiting a response regarding that) and the coding issues I'm seeing can be resolved soon. I would really like to use this on some upcoming sites, but need the bugs do be worked out before I can do that.

Using the Twenty Twelve theme, I observed 16 errors and warnings within the Listing Search Widget. Partial list includes:

Stray end tag ul
Duplicate ID post_type
Duplicate ID property_status
Duplicate ID property_location
Duplicate ID property_category
Duplicate ID property_price_form
Duplicate ID property_price_to

Will those issues be addressed in the near future?

Thanks!

**Comment by mediatelecom** [comment]
Can I get to see related errors/warnings

**Comment by mervb** [comment]
Sarah Large replied
Dec 2, 11:10pm
in the rental/archive listing page where you can show grid or list view of the listings - the end </li> tag seems wrong???

</li data-view="grid">

??

The actual HTML is shown here for you 

<ul>
<li title="List" class="epl-current-view view-list" data-view="list">
</li>
<li title="Grid" class="view-grid" data-view="grid">
</li data-view="grid">
</ul>

Thank you 
Sarah

**Comment by mervb** [comment]
complete

**Comment by mervb** [comment]
added to change log
