### ISSUE TITLE
Google Maps CSS issue with some themes

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#139]
#epl-default-map .gm-style img,
.epl_adv_tab_map .gm-style img {
    max-width: none;
    box-shadow: none;
}

**Comment by mediatelecom** [comment]
https://github.com/mediatelecom/Easy-Property-Listings/commit/350270bd173ec2ef5debd647fd4682cdb53ebed2

**Comment by mervb** [comment]
complete

**Comment by mervb** [comment]
added to change log
