### ISSUE TITLE
uncaught exception redisexception due to session_start

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#140]
Session Start error caused with Divi theme and potentially session incompatibility in some server cases.

![error-preint-screen](https://cloud.githubusercontent.com/assets/4696393/10662223/a2563ef6-78e5-11e5-9fac-1f0481f0110f.jpg)

**Comment by mediatelecom** [comment]
https://github.com/mediatelecom/Easy-Property-Listings/commit/5fad7387f02de31fcd21364b8372e94d42234925

**Comment by mervb** [comment]
Further Improve session start. Some other themes/plugins may already call this function and I get a notice

Notice: A session had already been started - ignoring session_start() in /Users/Merv/Sites/easypropertylistings-dev/wp-content/themes/hudson_homes/header.php on line 1

**Comment by mediatelecom** [comment]
we already have     if(!session_id()) {
        session_start();
    } to check if session already exists same check should be there in theme as well if the theme is initalising a session, we cant do much about it . also its not standard to declare session_start in header file which is executed so late . always session_start should be started in a hook's callback like we did in init hook

**Comment by epl-dev** [comment]
this ias already been fixed

**Comment by mervb** [comment]
Added to change log
