### ISSUE TITLE
LinkedIn URLs are wrong

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#146]
Hey, in the social links you've got:

http://au.linkedin.com/in/

But the latest URL structure for profile URLs are:

https://au.linkedin.com/pub/katie-knight/16/788/187

So if I put in the user profile:

pub/katie-knight/16/788/187

It creates a broken link:

http://au.linkedin.com/in/pub/katie-knight/16/788/187

**Comment by mervb** [comment]
Added to change log

**Comment by SimeonGriggs** [comment]
This appears to be broken again. 

Even if I insert a URL that doesn't contain 'linkedin' it will create a link to `www.linkedin.com/pub` without the `http://` and now the URLs shouldn't have `/pub/` in them...

Would much prefer the plugin just use a complete URL and not try to be too clever :|
