### ISSUE TITLE
Translation issue with Russian

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#170]
Please see below which fields I mean:

Ensuite
Fully Fenced
Security System
Ducted Heating
Listing Agent
Second Listing Agent
House and Land Package

Another issues:

"Pay TV" - displaying only in English, no Russian version

"Toilet" - not displaying from small letter in listing, only from capital
"Garage" - not displaying from small letter in listing, only from capital
"Carport" - not displaying from small letter in listing, only from capital

As for the units:
hectare - no translation on frontend
m2 - no translation on frontend

**Comment by epl-dev** [comment]
all strings are passed with __ function cant find the issue

**Comment by mervb** [comment]
Added to change log
