### ISSUE TITLE
Possible Date Selection conflict, can we improve our function to prevent conflict

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#181]
HS Ticket

**Default EPL Calendar Selection**

![2016-03-03 calendar selection possible conflict - this is epl style](https://cloud.githubusercontent.com/assets/4696393/13491784/692459ae-e16f-11e5-81f9-8e2d68b07219.png)

**Possible Conflict**

![2016-03-03 calendar selection possible conflict - not normal epl style](https://cloud.githubusercontent.com/assets/4696393/13491798/7620fff4-e16f-11e5-9265-54b1bcfd3b4a.png)

**Comment by epl-dev** [comment]
not issue in our code , checked .  which plugin is conflicting ?

**Comment by mervb** [comment]
unsure i missed the HS ticket for you to check.

https://secure.helpscout.net/conversation/177498100/1882/?folderId=625687
