### ISSUE TITLE
3.3 import / export settings

### ISSUE THREAD

**Issue by wpdevstudio** [easypropertylistings/Easy-Property-Listings#292]

**Comment by mervb** [comment]
Added tools for this, Can we also export and import extension settings?

**Comment by mervb** [comment]
Export Tools Page changes

![Export Tools](https://user-images.githubusercontent.com/4696393/55859023-b8d0cf80-5ba3-11e9-8433-dfb2dc9587af.jpg)

**Comment by wpdevstudio** [comment]
Merv it already import all extension data.
