### ISSUE TITLE
3.1: Pagination bug when on EPL location taxonomy

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#306]
HS Ticket
https://secure.helpscout.net/conversation/219182343/2716/?folderId=625684

The site has been running well for us. We just noticed an issue with
pagination using our custom taxonomy for Land. Has this happened before?

Works fine on our regular listings page: http://walleyproperties.com/land/

When filtering by County and then going to page 2 we get:
http://walleyproperties.com/county/jones-mississippi/page/2/
​

**Comment by wpdevstudio** [comment]
404 issue was in custom taxonomy .. seems to  be not a bug but flush rewrite issues
