### ISSUE TITLE
Problem with coordinates map

### ISSUE THREAD

**Issue by PascalBG** [easypropertylistings/Easy-Property-Listings#316]
Hi,

Since approx 1 week the map visible for the visitors does not show the exact location of the coordinates.
It does in the control panel.
Solved it by installing easy listings map but looks like there is a bug in the regular map.

**Comment by envoys** [comment]
Same issues here. Using EPL search it does not zoom in on the location searched for but works fine in admin panel and on the listing page. Any way to fix the search page?
