### ISSUE TITLE
Featured columns  titles and display like they do in the backend

### ISSUE THREAD

**Issue by wpdevstudio** [easypropertylistings/Easy-Property-Listings#319]

**Comment by wpdevstudio** [comment]
ticket id 

# 3602

**Comment by mervb** [comment]
Ticket Notes

Hi there, I just have some suggestions with the Features sections.

Why are there 'main' features under "House Features", and then "Additional Features" when they all show up in the same place in the listing?

There should be an easier way to add features. I know they can be added as "features taxonomy', but then they show up as hyperlinked tags which is confusing for the general viewer. They click on those thinking it's details about the feature, then get taken to a page of listings with those features. Only someone who setup the site would know why they are there. It's would be better to just be able to add to the preconfigured features easily, and be able to check them off so they display just like the other features with no links.

Why are their separate lists of features (indoor, outdoor etc.) when they all show up in the same list anyway? Why not have those columns have titles and display like they do in the backend? With no headers, again, no one but the person setting up the site knows what those lists actually are. It just looks like one bulk list.

I looked into the premium listings templates available, and none of them seem to address these issues, so I submitting this as a request.
