### ISSUE TITLE
3.3 Search by linked contacts

### ISSUE THREAD

**Issue by vmechele** [easypropertylistings/Easy-Property-Listings#449]
Hi Merv,

Is there any way to add a search on the linked contacts? I would like to be able to get all the listings which are linked to contact ***. Is this possible if so how?

Furthermore I would also like to add the linked contacts in the backend. Is this possible?

Thanks a lot!

KR,

Vincent

**Comment by mervb** [comment]
Review for 3.3

**Comment by mervb** [comment]
Uncertain, please review @lead dev
