### ISSUE TITLE
3.3 Shortcode Sort Current Sold Enhancement

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#487]
When using shortcodes and setting the status to say current, sold or leased and tools top enabled 

The tool area displays the **Status** sorting filter options which are not needed as they are all the same. So when specifying the status in the shortcodes, remove the Status sorting options

Status : Current First
Status : Sold/Leased First

**Codex Example**
[How to Disable Suburb A-Z filter options](http://codex.easypropertylistings.com.au/article/305-how-to-disable-suburb-a-z-filter-options)

[HS Ticket](https://secure.helpscout.net/conversation/405786018/5574/?folderId=625690)

**Comment by mervb** [comment]
Implement with new filter in core (might already be done)

**Comment by wpdevstudio** [comment]
already implemented
