### ISSUE TITLE
3.3 Acre to Acres tweak - Implement formatting for measurements

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#489]
I have another question… How would I change "Acre" to "Acres" when it displays on the property listing page? So it says 10.3 acres instead of 10.3 acre.

**Comment by mervb** [comment]
Implement (might already be in 3.3)

**Comment by mervb** [comment]
Just received a ticket on this today HS 9954

**Comment by wpdevstudio** [comment]
done
