### ISSUE TITLE
3.2 Search Widget Order Filter not working on multiple tax query

### ISSUE THREAD

**Issue by avikour** [easypropertylistings/Easy-Property-Listings#494]
**Warning: array_multisort(): Array sizes are inconsistent in --- \easy-property-listings\lib\widgets\widget-functions.php on line 695**

**Comment by avikour** [comment]
Change lines 690-694 with this:

foreach($fields as $field_key   =>  $field_value) {
		$fields[$field_value['meta_key']] = $field_value;
		$order[$field_value['meta_key']] = isset($field_value['order']) ? $field_value['order'] : 20;
		unset($fields[$field_key]);
	}

**Comment by mervb** [comment]
resolved
