### ISSUE TITLE
3.2 Agent Widget

### ISSUE THREAD

**Issue by ryanrphillips** [easypropertylistings/Easy-Property-Listings#496]
Still needs to be investigated. There seems to be an issue when assigning two agents to a listing and having a different agent as the author of the listing. All three agents show up in the widget and the markup for the first agent is broken.

**Comment by ryanrphillips** [comment]
Was able to confirm this on my localhost. The listing has two agents assigned, but when using the author widget, the first agent is replaced by the author of the post itself. The second agent displays correctly.

We should change the logic to use the first agent if available, if not, use the post author.

**Comment by mervb** [comment]
Yes i've seen this before, also if there is no staff directory author all staff images appear on the widget
