### ISSUE TITLE
3.3 ACF returns image URL on first page, but image ID on all pages after

### ISSUE THREAD

**Issue by ryanrphillips** [easypropertylistings/Easy-Property-Listings#503]
From client:

With regard to the image ID thing, I've managed to fix it by setting the ACF field to return an ID and utilising wp_get_attachment_url() but I thought it might be worth bringing to your attention that if an ACF image field is called in a template with pagination and it is set to return the image URL, on every page past the first page, that field returns an ID instead. Not sure exactly why but I'm guessing some sort of conflict with ACF and EPL perhaps? I've managed to rectify it by forcing it to return an ID in the field settings but I figured it might be worth bringing to your attention in any case.

Ticket:

https://secure.helpscout.net/conversation/452426377/6279?folderId=1592661

This one needs testing to confirm what could be causing it.

**Comment by mervb** [comment]
Sliders Extension is built for this
