### ISSUE TITLE
3.3 Google Map: Show suburb if street not found

### ISSUE THREAD

**Issue by ryanrphillips** [easypropertylistings/Easy-Property-Listings#511]
Suggestion via ticket: https://secure.helpscout.net/conversation/471242090/6529?folderId=625689

Sounds like a good idea. If Google can't find the street for whatever reason, we could zoom in on the suburb instead.

**Comment by mervb** [comment]
Can we highlight the suburb INSTEAD of dropping a PIN in the case where we the DISPLAY Address is NOT ticked?

**Comment by wpdevstudio** [comment]
re the original request : geocode by suburb if street address give zero results. Street address also includes suburb state postcode etc while geocoding and if any of the address components are a match to google, it will throw results 

example :

https://maps.google.com/maps/api/geocode/json?address=some street that will never exist,Thornton, NSW 2322&sensor=false&key=INSERT API KEY HERE

this returns result.

**Comment by wpdevstudio** [comment]
ie google automatically does it. if in address street can't be geocoded it returns suburb geocode
