### ISSUE TITLE
Multisite compatible?

### ISSUE THREAD

**Issue by bash88** [easypropertylistings/Easy-Property-Listings#517]
Hi Merv,

Really like the plugin from what I've initially read. Seems like it can meet all requirements I have. 

Just one thing left that I can't find anywhere in the documentation or description. Is the plugin multisite compatible? Are there any problems I can expect to run into when incorporating this plugin in different instances in a WordPress Multisite environment?

Hope to hear from you soon so I can decide to use your plugin and buy support for my project.

Regards,
Bas

**Comment by mervb** [comment]
Yes the plugin is multisite compatible, we use multisite to configure our Theme Demos site
http://easypropertylistings.com.au/demo/themes/jupiter/

Other Demos running on single Multisite
http://codex.easypropertylistings.com.au/article/185-theme-templates
