### ISSUE TITLE
3.3 Pagination and multiple shortcodes on the same page

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#549]
Ability to add the same shortcode on a page and have pagination work for both

perhaps and additional shortcode option for a different paged id patched into 3.2 

https://wordpress.stackexchange.com/questions/47259/multiple-wp-query-loops-with-pagination 

Eg pagination_id=2

SHORTCODE OPTIONS (added one at the end)

$attributes = shortcode_atts( array(
'post_type'	=> $property_types, //Post Type
'status'	=> array( 'current', 'sold', 'leased' ),
'limit'	=> '10', // Number of maximum posts to show
'offset'	=> '', // Offset posts. When used, pagination is disabled
'author'	=> '',	// Author of listings.
'featured'	=> 0,	// Featured listings.
'template'	=> false, // Template can be set to "slim" for home open style template
'location'	=> '', // Location slug. Should be a name like sorrento
'tools_top'	=> 'off', // Tools before the loop like Sorter and Grid on or off
'tools_bottom'	=> 'off', // Tools after the loop like pagination on or off
'sortby'	=> '', // Options: price, date : Default date
'sort_order'	=> 'DESC', // Sort by ASC or DESC
'query_object'	=> '', // only for internal use . if provided use it instead of custom query
'pagination'	=> 'on', // Enable or disable pagination
'pagination_id'	=> '' // Change when using multiple shortcodes on the same page
), $atts );

**Comment by wpdevstudio** [comment]
feature added for pagination for multiple shortcodes on same page. need to pass instance_id in shortcode to make it work.

example [listing instance_id="3"] 

also added some tweaks for shortcode query in general 

> filters for shortcode query arguments
> 3 query vars to target specific shortcode queries :
1. is_epl_shortcode ( target all epl shortcode )
2. epl_shortcode_name ( target shortcode query based on shortcode example only target listing shortcode using this :
$query->get('epl_shortcode_name') == 'listing' in pre_get_post
3. instance_id. allows us to target specific query for same shortcode
example 
if( $query->get('epl_shortcode_name') == 'listing'  && $query->get('instance_id') == '4'  ) {
$query->set('posts_per_page',20);
}
