### ISSUE TITLE
Not working googlmaps in 1.3 (dev Beta 4)

### ISSUE THREAD

**Issue by aleks-nl5** [easypropertylistings/Easy-Property-Listings#55]
Good day.
In ver. 1.3 (dev Beta 4) when add the address, info map does not display the location when Address language is "Ukrainian" or "Russian".
Only when the coordinates manually added (e.g. 48.473921, 35.023990) or Address write in "English".
In ver. from wordpress.org (1.2.1) address in both languages is OK.

**Comment by aleks-nl5** [comment]
Yes, example address (the same problem with other Cyrillic addresses) :
- work: “48.396224,35.0535622” & “5, Startova, Dnipropetrovs’k, Ukraine”
- don’t work: “5, Стартовая, Днепропетровск, Украина”
PS I duplicated at "easypropertylistings_dot_com_dot_au/support/topic/not-working-googlmaps-in-1-3-dev-beta-4/" just in case

**Comment by aleks-nl5** [comment]
Tested the new version in the admin - everything and left, and when you view a single listing - the map is displayed correctly! Thank U!
PS. Also, many thanks for a smooth grid-view (rather than Pinterest Like Grid) is really more beautiful !!!

**Comment by mervb** [comment]
Thanks for letting me know that its all fixed!
