### ISSUE TITLE
3.3 [BUG] "Garage" and "Open Parking" seems to overlap

### ISSUE THREAD

**Issue by ChriKn** [easypropertylistings/Easy-Property-Listings#574]
When adding a number for the "garage" section it automatically adds the same number for "open parking"
Bizarrely, when using the number 1 the display numbers are "1 open parking(s)" and "  garage(s)"
The language used is french, same bug is also present in german.

I have found no mentions of this on github or the Wordpress forums.

**Comment by wpdevstudio** [comment]
not an issue. 
Parking space = garage + carport
so, if garage = 1 , carport = 0
then
parking space  = 1 as well

Another example :
4 Garage
3 Carport
=
7 Parking Spaces
