### ISSUE TITLE
Translation of permalinks

### ISSUE THREAD

**Issue by Hostert** [easypropertylistings/Easy-Property-Listings#584]
Hello.

I'm testing your plugin and I see almost a 100% of it is already translated in pt-br.
But, even when using it in my language, when I create the blank pages for categories in my language, I still see the properties being created under the english permalink.

Example:

Enabled types:

Property - Imóvel - site/imovel/
Rent - Aluguel - site/aluguel/
First test property - Rua teste, 123 - site/property/rua-teste-123

I think the created property or rent, or any type should use my blank page created.
And, when your getting started says to save the permalinks structure, I don't know exactly if something have to be changed to this work.

Can you clarify and tell me if is possible to see my pages using the translated permalink, like site/imovel/rua-teste-123 ?

Thanks

**Comment by mervb** [comment]
Sorry for the terrible long delay in getting to you on this. The Codex has how to rename permalinks here
https://codex.easypropertylistings.com.au/article/114-change-the-slug-of-listing-post-types
