### ISSUE TITLE
3.3 Ability to add agent ID in author widget

### ISSUE THREAD

**Issue by avikour** [easypropertylistings/Easy-Property-Listings#585]
Need ability to show selected agent using ID

**Comment by mervb** [comment]
Add a field

![Author User ID](https://user-images.githubusercontent.com/4696393/55856253-50322480-5b9c-11e9-99bc-b30f34da3e66.jpg)

**Comment by wpdevstudio** [comment]
featured applied as per screenshot ie multi user support
