### ISSUE TITLE
3.3 Ability to load a different template based on status or other variable

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#594]

**Comment by mervb** [comment]
Can we improve this hook where we specify another template through the hook?

<?php do_action( 'epl_property_blog' ); ?>

EG

<?php do_action( 'epl_property_blog' , 'name-is-cool' ); ?>

Doing this would then load the file 


I think we just need to specify priority and parameters here?
https://github.com/easypropertylistings/Easy-Property-Listings/blob/315c18215494b50b148ce7d843ff05be096e8ea0/lib/includes/template-functions.php#L330

add_action('epl_property_blog','epl_property_blog');

EG

add_action('epl_property_blog','epl_property_blog' , 10 , 1);

SAME with single

<?php do_action( 'epl_property_single' ); ?>

https://github.com/easypropertylistings/Easy-Property-Listings/blob/315c18215494b50b148ce7d843ff05be096e8ea0/lib/includes/template-functions.php#L93

add_action('epl_property_single','epl_property_single');

TO

add_action('epl_property_single','epl_property_single' , 10 , 1 );

**Comment by wpdevstudio** [comment]
added filter for template file which can be used to change template based on meta fields
