### ISSUE TITLE
3.3 FIX for Divi / Elementor and Search White Screen in Admin

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#595]
[HS 8962](https://secure.helpscout.net/conversation/703692769/8962?folderId=625690)

Remember the search breaking in the admin in some cases like Divi and Elementor. Looks like a quick easy core fix that you can implement.

---

I've created a custom sidebar with "EPL - Listing Search" widget, then I've included that sidebar in a page with DIVI Page Builder.

The widget is correctly shown in frontend, but the page is not more accessible in wordpress backend: a blank page is shown.

This is the error:

PHP Fatal error: Call to undefined function epl_shortcode_listing_search_callback() in /home/admin/web/demo4.primisuimotori.it/public_html/8/immobiliare2/wp-content/plugins/easy-property-listings/lib/widgets/widget-listing-search.php on line 42

I've fix it by editing widget-listing-search.php in line 42 with this :

if ( ! is_admin() ) {

echo epl_shortcode_listing_search_callback($instance);

}

Now I can correctly edit the page with the DIVI Builder.

**Comment by wpdevstudio** [comment]
fix applied
