### ISSUE TITLE
Translate error Author box

### ISSUE THREAD

**Issue by aleks-nl5** [easypropertylistings/Easy-Property-Listings#62]
Hi Merv!
When translating using .pot file from '1.3-public-beta3', source code "About" for example "О авторе" on single listing page in the Author box, an error:
"Warning: call_user_func () expects parameter 1 to be a valid callback, function 'epl_author_tab_О_авторе' not found or invalid function name in/home/u780900897/public_html/wp-content/plugins/Easy-Property-Listings-1.3-public-beta-3/lib/templates/content/content-author-box.php on line 42 ".

The source code "About" refers to the file "/lib/includes/template-functions.php" line №918
![err](https://cloud.githubusercontent.com/assets/10290786/5775955/af079dd0-9d89-11e4-8746-8c72ec654f65.png)

**Comment by mervb** [comment]
This is fixed now for you Alex?

**Comment by aleks-nl5** [comment]
Hi Merv, just updated to 2.0.3 and using the new pot-file - for the purity of the experiment, translated only one word - "About".
Unfortunately - the same error.
PS. The error is independent of the translation - it can be any word.
