### ISSUE TITLE
Missing translation in pot file

### ISSUE THREAD

**Issue by aleks-nl5** [easypropertylistings/Easy-Property-Listings#70]
Hi Merv!
I'm finished translation to Russian lang. when started to check translation I saw in dashboard EPL widget not fully translated, here screenshot (no translated: widget header, type of property).
Also translation missing in admin in "status" column and under graph bar - "under offer" (screenshot below).
Else seems okay.
![db_widget](https://cloud.githubusercontent.com/assets/10290786/5842801/8b96f578-a1b0-11e4-812b-901d733ab5a3.png)
![status](https://cloud.githubusercontent.com/assets/10290786/5842955/b83b14b4-a1b1-11e4-8f69-c748afd7456a.png)
![underoffer](https://cloud.githubusercontent.com/assets/10290786/5842960/bc56b4d6-a1b1-11e4-90b8-6333731e73b2.png)

**Comment by mervb** [comment]
champ, thanks will implement these
