### ISSUE TITLE
Vulnerabilities in Easy Property Listings plugin.

### ISSUE THREAD

**Issue by inakahara** [easypropertylistings/Easy-Property-Listings#736]
Dear Merv Barrett

Hi, I am Rei Nakahara, a member of Cryptography Laboratory in Tokyo Denki University.
We found vulnerabilities in your plugin.
Therefore, I would like to get in touch with the technical team so please give me an email address.

**Comment by mervb** [comment]
Please contact us through the support form here: https://easypropertylistings.com.au/contact/

**Comment by inakahara** [comment]
I tried to contact from this contact form(https://easypropertylistings.com.au/contact/) several times, but the form didn't seem to work and I couldn't submit the content.
Therefore, I got in touch with GIithub this time.

**Comment by inakahara** [comment]
> Please contact us through the support form here: https://easypropertylistings.com.au/contact/

I tried to contact from this contact form(https://easypropertylistings.com.au/contact/) several times, but the form didn't seem to work and I couldn't submit the content.
Therefore, I got in touch with GIithub this time.

**Comment by mervb** [comment]
You can email me on support at easypropertylistings.com.au

**Comment by mervb** [comment]
Got your email thanks, looking into it
