### ISSUE TITLE
Please contact us through the support form here: https://easypropertylistings.com.au/contact/

### ISSUE THREAD

**Issue by inakahara** [easypropertylistings/Easy-Property-Listings#738]
>Please contact us through the support form here: https://easypropertylistings.com.au/contact/

>_Originally posted by @mervb in https://github.com/easypropertylistings/Easy-Property-Listings/issues/736#issuecomment-508386667_

I tried to contact from this contact form(https://easypropertylistings.com.au/contact/) several times, but the form didn't seem to work and I couldn't submit the content.
Could you give me an alternative means of communication？

**Comment by mervb** [comment]
You can email me on mervb1@gmail.com
