### ISSUE TITLE
3.4 - EPL Search loads default language results (Polylang), not the actual language

### ISSUE THREAD

**Issue by nikkoch** [easypropertylistings/Easy-Property-Listings#755]
EPL Search loads default language results, not the actual language. However then, if we click the flag, it loads what we need, but sure it’s not the good way.

Here the link from Polylang developer: 
https://polylang.pro/always-use-get_search_form-to-create-search-forms/

WP Support topics:
https://wordpress.org/support/topic/polylang-and-easy-property-listings-search/#post-11785455

https://wordpress.org/support/topic/search-widget-language-not-working-polylang/#post-11786333

**Comment by mervb** [comment]
Tagged, working on security fixes then will tackle this for 3.4 build (next release)

**Comment by wpdevstudio** [comment]
not EPL issue. polylang attaches language identfier in URL way too late for home_url or site_url functions 

similar issue reported here :
https://wordpress.org/support/topic/wp-function-site_url-is-not-returning-the-localized-homepage-url/

the simplest fix for this is to copy template/content/shortcodes/listing-search/default.php to 
active theme/easypropertylistings/shortcodes/listing-search/default.php and it should work as expected

**Comment by nikkoch** [comment]
> not EPL issue. polylang attaches language identfier in URL way too late for home_url or site_url functions
> 
> similar issue reported here :
> https://wordpress.org/support/topic/wp-function-site_url-is-not-returning-the-localized-homepage-url/
> 
> the simplest fix for this is to copy template/content/shortcodes/listing-search/default.php to
> active theme/easypropertylistings/shortcodes/listing-search/default.php and it should work as expected
> 
> home_url when called from theme's template automatically add the necessary lang identifier for URLs

Hello guys and many thanks for your reply.
When you plan to release 3.4 update?
Also I tried mentioned by **wpdevstudio** solution with no luck.
