### ISSUE TITLE
"NEW" Label is not displayed

### ISSUE THREAD

**Issue by aleks-nl5** [easypropertylistings/Easy-Property-Listings#81]
Hi Merv!
From 1.3 and now in 2.0 in the settings panel appeared item “Keep Listings flagged New for”, but what I did not specify the value there – the label does not appear in the listings.
If I correctly understood, this label must appear on the pages listing over the images as well as in the “sold” or “under-offer”.

Twenty Twelwe – 1.6
WP – 4.1
Easy Property Listings – 2.0

Thank you!

**Comment by mervb** [comment]
This has been fixed in 2.1
