### ISSUE TITLE
Open house shows with empty spaces in inspection meta field

### ISSUE THREAD

**Issue by wpdevstudio** [easypropertylistings/Easy-Property-Listings#819]

**Comment by mervb** [comment]
Resolved in 3.4.6

= 3.4.6 September 9, 2019 =

* Tweak: Support for polygon tag in SVG icons.
* Fix: Price display error in admin columns on commercial listings types that were set to both sale and lease.
* Fix: Home open title appearing in admin columns when imported data was empty.
