### ISSUE TITLE
Property rent period translation broken

### ISSUE THREAD

**Issue by bash88** [easypropertylistings/Easy-Property-Listings#881]
Hi Merv,

I noticed the rent period wasn't translating anymore on my website. I traced down the problem to /lib/includes/class-epl-property-meta.php at line 787. Fixed it by doing:

`$price .= '<span class="rent-period">' . $epl_property_price_rent_separator . '' . __( ucfirst( $this->get_property_meta( 'property_rent_period' ) ), 'easy-property-listings' ) . '</span>';`

**Comment by mervb** [comment]
Thanks for letting us know, this has been fixed in 3.4.27
