### ISSUE TITLE
3.5 Conditional show hide capability to Core as a feature.. so that it can be used extension wide

### ISSUE THREAD

**Issue by prince5ingh** [easypropertylistings/Easy-Property-Listings#888]
`array(
	'name'	=>	'field_name',
	'type'	=>	'text',
	// show if property_type is house or townhouse
	'data-show' => array(
		'property_type' => array(
			'house',
			'townhouse'
		)
	)
)`

**Comment by mervb** [comment]
added in 3.5 for extensions settings
