### ISSUE TITLE
Widget Override not using format

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#89]
I have worked out generally how templates work by looking at your code (the documentation wasn’t too clear)

In essence most template are retrieved by epl_get_template_part() which in turn calls locate_template() wand there is a path easypropertylistings so if you drop templates into a directory in your child theme you can override.

You know that, of course and it works.

But is there any reason the widget-content-listing.php isn’t in this scheme?

line 370 of template-functions.php

include(EPL_PATH_TEMPLATES_CONTENT.'widget-content-listing.php');

I changed it to

epl_get_template_part('widget-content-listing.php');

And it appears to work fine picking up my custom template.

Of course it is typical that I need to customise that layout :(

Is this just an oversight? Can this go into the next release?

Best regards, Alan

**Comment by mervb** [comment]
Include this in 2.0.4

**Comment by mediatelecom** [comment]
fixed already

**Comment by mervb** [comment]
complete
