### ISSUE TITLE
3.5 Improve Stickers wrapper with filter or something to allow better (easier) custom html

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#945]
![properties_archive_-_neller](https://user-images.githubusercontent.com/4696393/104155301-db9bb200-5421-11eb-9333-0bde5b711e10.jpg)

this is difficult to achieve currently

![devtools_-_www_nellerre_com_au_property_](https://user-images.githubusercontent.com/4696393/104155322-e6eedd80-5421-11eb-954f-0078bd651248.jpg)

**Comment by prince5ingh** [comment]
basically from :
$price_sticker .= '<span class="status-sticker sold">' . $this->label_sold . '</span>';
to :
$price_sticker .= $this->render_single_sticker( $classes, $label, $add_wrapper);

**Comment by mervb** [comment]
Hook added to allow entire replacement of sticker code in 3.5
