### ISSUE TITLE
3.54.38 mp4 video support for Videos

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#947]
EG when adding 
https://inspectre.blob.core.windows.net/videolinkfiles/f53a2514-a8dd-747c-6c63-3a68a533710d/8_Pacific_Avenue_Miami_QLD_4220_Flyover_V1.mp4

To the video URL we can use the 

[video] shortcode in WordPress to output it. 
https://wordpress.org/support/article/video-shortcode/

**Comment by mervb** [comment]
Add .mov support also

**Comment by prince5ingh** [comment]
https://github.com/prince5ingh/Easy-Property-Listings/commit/26e8c2039cd3ed23057490feb5db4fc8f92a9896

**Comment by mervb** [comment]
added in 3.4.38
