### ISSUE TITLE
Need a help for creating property listings website 

### ISSUE THREAD

**Issue by siddiknmh** [easypropertylistings/Easy-Property-Listings#960]
Hello Dear Developer Team,

Actually, I need to create a property listings website for our company's client. They are asking for the same functionality as www.scala.cy this website also some extra functionality requirements. I checked the example website is not a WordPress website. That why I'm playing to use any comercial property listings plugin. But most plugins did not meet all of the functionality. So I need extra support from the plugins team for extra functionality requirements. 

Is your team give this type of extra support for extra functionality requirements ( I mean paid support)? 

Thanks in Advance

**Comment by mervb** [comment]
Can you please direct pre-sale tickets here:
https://easypropertylistings.com.au/pre-sale-question/

We can then communicate via email and the above is a good project that EPL can handle,
Thanks!
