### ISSUE TITLE
3.5 - JS issue with messaging said 5 (supports 50)

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#964]
![Easy-Property-Listings_meta-box-init_php_at_master_·_easypropertylistings_Easy-Property-Listings_and__19345_Price_on_For_Sale_property_-_Ado_I_Sharp_Design](https://user-images.githubusercontent.com/4696393/115322850-835f1380-a1b9-11eb-9c1c-4907c878b39b.png)

**Comment by prince5ingh** [comment]
@mervb maxlength is total length of value while JS error is for validation it supports decimal number with upto 5 digits after decimal.

**Comment by mervb** [comment]
ok thanks
