### ISSUE TITLE
I can´t configure Google Maps API Key

### ISSUE THREAD

**Issue by amattajm** [easypropertylistings/Easy-Property-Listings#968]
![imagen](https://user-images.githubusercontent.com/83413210/116567598-27456f00-a8de-11eb-827b-fa39cf1a9821.png)
There's no section to put the Key under Advanced

**Comment by mervb** [comment]
Looks like an old version of the plugin, update it. Also for support visit: https://easypropertylistings.com.au/support-ticket/
