### ISSUE TITLE
3.4.xx - get_property_land_value and get_property_building_area_value are returning if 0

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#979]
For some reason get_property_building_area_value and get_property_land_value are returning if 0 is set using

<?php echo $property->get_property_land_value( 't' ); ?>
<?php echo $property->get_property_building_area_value( 't' ); ?>

in template file

![Dentown_-_Expanse_-_Custom_Templates___Just_another_WordPress_site_and_Edit_Listing_‹_Dentown_-_Expanse_-_Custom_Templates_—_WordPress](https://user-images.githubusercontent.com/4696393/128132185-e684f2d9-a1bb-4990-bdd5-ec948dd4ae7a.jpg)

**Comment by prince5ingh** [comment]
For Land, fix is already here :
https://github.com/prince5ingh/Easy-Property-Listings/commit/b972b70c6d48a7d45a167c8efca350408a8b0081

**Comment by mervb** [comment]
Included in 3.4.38

**Comment by mervb** [comment]
Included in 3.4.38
