### ISSUE TITLE
3.4.xx - [listing_advanced] Shortcode not loading Listing Templates extensions templates

### ISSUE THREAD

**Issue by mervb** [easypropertylistings/Easy-Property-Listings#980]
Seem to have a bug with [listing_advanced] and listing templates add-on

eg [listing] or [listing_category]

![Test_Office_Shortcode___Gallelli_Real_Estate](https://user-images.githubusercontent.com/4696393/128675342-9667cfca-7606-42bc-8b22-c9c2bd0ccac2.jpg)

3:55
--- ie correct

But with [listing_advanced]

not loading template

![Test_Office_Shortcode___Gallelli_Real_Estate](https://user-images.githubusercontent.com/4696393/128675298-1bd94ff0-2d85-475c-8c7e-c4ade5b9109c.jpg)

Works if both
[listing_advanced] and [listing] are used on the same page

The Loop template has been selected in add-on

![Extensions_‹_Gallelli_Real_Estate_—_WordPress](https://user-images.githubusercontent.com/4696393/128675450-289b03d7-0d21-4449-96f4-52dc83dfb532.jpg)

**Comment by prince5ingh** [comment]
@mervb issue was in listing templates not core, fixed here :

https://github.com/prince5ingh/epl-listing-templates/commit/628e7f0dcd4800282490f3c103c674d209be1266
